# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Merced Collective Action Network
email: hey@mercedcan.com
description: We defend progressive values in policymaking at the local, state, and federal levels.
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username: jekyll

countdown:
  election_date: 2016-11-09
  inauguration_date: 2017-01-20
  midterm_date: 2018-11-06

defaults:
  - scope:
      path: ""
      type: events
    values:
      layout: event

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock